services:
  # 1. Database 
  db:
    image: mcr.microsoft.com/mssql/rhel/server:2025-latest
    container_name: db-local
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Nhatminh03
    ports:
      - "1433:1433"
    networks:
      - mealplanner-api-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Nhatminh03 -Q 'SELECT 1' -No"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    
  # 3. Migrator
  migrator:
    build:
      context: .
      dockerfile: src/MealPlannerAPI.DbMigrator/Dockerfile
    container_name: mealplanner-api-migrator
    environment:
      - ConnectionStrings__Default=Server=db,1433;Database=MealPlannerAPI;TrustServerCertificate=True;User ID=sa;Password=Nhatminh03
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mealplanner-api-network

  # 4. The API Host
  web-api:
    build:
      context: .
      dockerfile: src/MealPlannerAPI.HttpApi.Host/Dockerfile
    container_name: meal-planner-api-host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:81
      - ConnectionStrings__Default=Server=db,1433;Database=MealPlannerAPI;TrustServerCertificate=True;User ID=sa;Password=Nhatminh03
      - ConnectionStrings__Redis=redis:6379
      - App__HealthUiCheckUrl=http://localhost:81/health-status
    ports:
      - "44339:81"
    depends_on:
      migrator:
        condition: service_completed_successfully
    networks:
      - mealplanner-api-network
  # 5. The Blazor Web Admin Host UI
  blazor-web-admin:
    build:
      context: .
      dockerfile: src/MealPlannerAPI.BlazorHost/Dockerfile
    container_name: meal-planner-blazor-host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:82
      - ConnectionStrings__Default=Server=db,1433;Database=MealPlannerAPI;TrustServerCertificate=True;User ID=sa;Password=Nhatminh03
      - App__HealthUiCheckUrl=http://localhost:82/health-status
    ports:
      - "58376:82"
    depends_on:
      migrator:
        condition: service_completed_successfully
    networks:
      - mealplanner-api-network
networks:
  mealplanner-api-network:
    driver: bridge